name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1

      - name: build
        run: deno task build

      - name: git setting
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
      - name: Git push
        run: |
          git add .
          git commit -m "Build js." | true
          git push | true
